# Generated by Django 5.0.2 on 2024-03-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
